local nvim_set_hl = vim.api.nvim_set_hl

local Colorscheme = {}

function Colorscheme.setup()
  vim.o.termguicolors = true

  -- Neovim default higlight group
  nvim_set_hl(0, "ColorColumn", { bg = "#D5D4E0" })
  nvim_set_hl(0, "Conceal", { bg = "#aba9c0" })
  --nvim_set_hl(0,'CurSearch',{fg=})
  nvim_set_hl(0, "Cursor", { fg = "#AFB5C6", bg = "#9CA6B9" })
  nvim_set_hl(0, "lCursor", { fg = "#AFB5C6", bg = "#9CA6B9" })
  nvim_set_hl(0, "CursorIM", { fg = "#7F8E9D", bg = "#9CA6B9" })
  nvim_set_hl(0, "CursorColumn", { fg = "#608397", bg = "#E6E6F1" })
  nvim_set_hl(0, "CursorLine", { bg = "#D7D7E2" })
  nvim_set_hl(0, "Directory", { fg = "#436595" })
  nvim_set_hl(0, "DiffAdd", { fg = "#698271", bg = "#E6E6F1" })
  nvim_set_hl(0, "DiffChange", { fg = "#608397", bg = "#E6E6F1" })
  nvim_set_hl(0, "DiffDelete", { fg = "#ba3d5a", bg = "#E6E6F1" })
  nvim_set_hl(0, "DiffText", { fg = "#e59368", bg = "#E6E6F1" })
  nvim_set_hl(0, "EndOfBuffer", { fg = "#E6E6F1" })
  -- nvim_set_hl(0,'TermCursor',{fg})
  -- nvim_set_hl(0,TermCursorNC
  nvim_set_hl(0, "ErrorMsg", { fg = "#ba3d5a", bg = "#E6E6F1", italic = true })
  nvim_set_hl(0, "WinSeparator", { fg = "#D5D4E0", bg = "#E6E6F1" })
  nvim_set_hl(0, "Folded", { fg = "#7F8E9D", bg = "#D7D7E2" })
  nvim_set_hl(0, "FoldColumn", { fg = "#9CA6B9", bg = "#D5D4E0" })
  nvim_set_hl(0, "SignColumn", { fg = "#436595", bg = "#E6E6F1" })
  nvim_set_hl(0, "IncSearch", { fg = "#8787BF", bg = "#D5D4E0" })
  nvim_set_hl(0, "Substitute", { fg = "#E6E6F1", bg = "#ba3d5a", bold = true })
  nvim_set_hl(0, "LineNr", { fg = "#aba9c0", bg = "#E6E6F1" })
  --nvim_set_hl(0,'LineNrAbove',{fg=})
  --nvim_set_hl(0,'LineNrBelow',{fg=})
  nvim_set_hl(0, "CursorLineNr", { fg = "#414560", bg = "#D5D4E0" })
  --nvim_set_hl(0,'CursorLineFold',{fg=})
  --nvim_set_hl(0,'CursorLineSign',{fg=})
  nvim_set_hl(0, "MatchParen", { fg = "#608397", bg = "#7F8E9D" })
  nvim_set_hl(0, "ModeMsg", { fg = "#708190" })
  --nvim_set_hl(0,'MsgArea',{fg=})
  --nvim_set_hl(0,'MsgSeparator',{fg=})
  nvim_set_hl(0, "MoreMsg", { fg = "#608397", bg = "#7F8E9D" })
  nvim_set_hl(0, "NonText", { fg = "#708190", bg = "#7F8E9D" })
  nvim_set_hl(0, "Normal", { fg = "#4e5a64", bg = "#E6E6F1" })
  nvim_set_hl(0, "NormalFloat", { fg = "#4e5a64", bg = "#f6f6fa" })
  --nvim_set_hl(0,'FloatBorder',{fg=})
  --nvim_set_hl(0,'FloatTitle',{fg=}f)
  --nvim_set_hl(0,'FloatFooter',{fg=})
  --nvim_set_hl(0,'NormalNC',{fg=})
  nvim_set_hl(0, "Pmenu", { fg = "#708190", bg = "#D5D4E0" })
  nvim_set_hl(0, "PmenuSel", { fg = "#608397", bg = "#f3f2f5" })
  --nvim_set_hl(0,'PmenuKind',{fg=})
  --nvim_set_hl(0,'PmenuKindSel',{fg=})
  --nvim_set_hl(0,'PmenuExtra',{fg=})
  --nvim_set_hl(0,'PmenuExtraSel',{fg=})
  nvim_set_hl(0, "PmenuSbar", { fg = "#708190", bg = "#D5D4E0" })
  nvim_set_hl(0, "PmenuThumb", { fg = "#608397", bg = "#D5D4E0" })
  nvim_set_hl(0, "Question", { fg = "#4e5a64" })
  --nvim_set_hl(0,'QuickFixLine',{fg=})
  nvim_set_hl(0, "Search", { fg = "#E6E6F1", bg = "#436595" })
  nvim_set_hl(0, "SpecialKey", { fg = "#7F8E9D" })
  nvim_set_hl(0, "SpellBad", { fg = "#ba3d5a", bg = "#D5D4E0", undercurl = true })
  nvim_set_hl(0, "SpellCap", { fg = "#e59368", bg = "#D5D4E0", undercurl = true })
  nvim_set_hl(0, "SpellLocal", { fg = "#D66652", bg = "#D5D4E0", undercurl = true })
  nvim_set_hl(0, "SpellRare", { fg = "#436595", bg = "#D5D4E0", undercurl = true })
  nvim_set_hl(0, "StatusLine", { fg = "#E6E6F1", bg = "#CCCBD9" })
  nvim_set_hl(0, "StatusLineNC", { fg = "#D5D4E0", bg = "#E6E6F1" })
  nvim_set_hl(0, "TabLine", { fg = "#708190", bg = "#E6E6F1" })
  nvim_set_hl(0, "TabLineFill", { fg = "#436595", bg = "#D5D4E0" })
  nvim_set_hl(0, "TabLineSel", { fg = "#aba9c0", bg = "#E06B6B" })
  --nvim_set_hl(0,'Title',{fg=})
  nvim_set_hl(0, "Visual", { bg = "#D5D4E0" })
  nvim_set_hl(0, "VisualNOS", { bg = "#D5D4E0" })
  --nvim_set_hl(0,'WarningMsg',{fg=})
  nvim_set_hl(0, "Whitespace", { bg = "#D5D4E0" })
  nvim_set_hl(0, "WildMenu", { fg = "#436595" })
  --nvim_set_hl(0,'WinBar',{fg=})
  --nvim_set_hl(0,'WinBarNC',{fg=})
  --nvim_set_hl(0,'Menu',{fg=})
  -- nvim_set_hl(0,'Scrollbar',{fg=})
  --nvim_set_hl(0,'Tooltip',{fg=})

  -- Builtin Neovim syntax
  nvim_set_hl(0, "Comment", { fg = "#aba9c0", italic = true })
  nvim_set_hl(0, "Constant", { fg = "#8787BF" })
  nvim_set_hl(0, "String", { fg = "#698271" })
  nvim_set_hl(0, "Character", { fg = "#698271" })
  nvim_set_hl(0, "Number", { fg = "#D66652" })
  nvim_set_hl(0, "Boolean", { fg = "#D66652" })
  nvim_set_hl(0, "Float", { fg = "#ba3d5a" })
  nvim_set_hl(0, "Identifier", { fg = "#ba3d5a" })
  nvim_set_hl(0, "Function", { fg = "#608397", italic = true })
  nvim_set_hl(0, "Statement", { fg = "#436595" })
  nvim_set_hl(0, "Conditional", { fg = "#608397" })
  nvim_set_hl(0, "Repeat", { fg = "#e59368" })
  nvim_set_hl(0, "Label", { fg = "#e59368" })
  nvim_set_hl(0, "Operator", { fg = "#ba3d5a", bold = true })
  nvim_set_hl(0, "Keyword", { fg = "#ba3d5a", italic = true })
  nvim_set_hl(0, "Exception", { fg = "#8787BF" })
  nvim_set_hl(0, "PreProc", { fg = "#8787BF" })
  nvim_set_hl(0, "Include", { fg = "#436595" })
  nvim_set_hl(0, "Define", { link = "Macro" })
  nvim_set_hl(0, "Macro", { fg = "#8787BF" })
  nvim_set_hl(0, "PreCondit", { link = "PreProc" })
  nvim_set_hl(0, "Type", { fg = "#e59368", italic = true })
  nvim_set_hl(0, "StorageClass", { fg = "#e59368" })
  nvim_set_hl(0, "Structure", { fg = "#e59368" })
  nvim_set_hl(0, "Typedef", { fg = "#e59368" })
  nvim_set_hl(0, "Special", { fg = "#e59368", italic = true })
  nvim_set_hl(0, "SpecialChar", { fg = "#e59368" })
  nvim_set_hl(0, "Tag", { fg = "#e59368" })
  nvim_set_hl(0, "Delimiter", { fg = "#436595" })
  nvim_set_hl(0, "SpecialComment", { fg = "#7F8E9D", italic = true })
  -- nvim_set_hl(0, "Debug", { fg =  })
  nvim_set_hl(0, "Underlined", { underline = true })
  -- --nvim_set_hl(0,'Ignore',{fg=})
  nvim_set_hl(0, "Error", { fg = "#ba3d5a", bg = "#D5D4E0", italic = true })
  nvim_set_hl(0, "Todo", { fg = "#8787BF", bg = "#D5D4E0" })

  -- Treesitter
  nvim_set_hl(0, "@text.literal", { link = "Comment" })
  nvim_set_hl(0, "@text.reference", { link = "Identifier" })
  nvim_set_hl(0, "@text.title", { link = "Title" })
  nvim_set_hl(0, "@text.uri", { link = "Underlined" })
  nvim_set_hl(0, "@text.underline", { link = "Underlined" })
  nvim_set_hl(0, "@text.todo", { link = "Todo" })
  nvim_set_hl(0, "@comment", { link = "Comment" })
  nvim_set_hl(0, "@punctuation", { link = "Delimiter" })
  nvim_set_hl(0, "@constant", { link = "Constant" })
  nvim_set_hl(0, "@constant.builtin", { link = "Special" })
  nvim_set_hl(0, "@constant.macro", { link = "Define" })
  nvim_set_hl(0, "@define", { link = "Define" })
  nvim_set_hl(0, "@macro", { link = "Macro" })
  nvim_set_hl(0, "@string", { link = "String" })
  nvim_set_hl(0, "@string.escape", { link = "SpecialChar" })
  nvim_set_hl(0, "@string.special", { link = "SpecialChar" })
  nvim_set_hl(0, "@character", { link = "Character" })
  nvim_set_hl(0, "@character.special", { link = "SpecialChar" })
  nvim_set_hl(0, "@number", { link = "Number" })
  nvim_set_hl(0, "@boolean", { link = "Boolean" })
  nvim_set_hl(0, "@float", { link = "Float" })
  nvim_set_hl(0, "@function", { link = "Function" })
  nvim_set_hl(0, "@function.builtin", { link = "Special" })
  nvim_set_hl(0, "@function.macro", { link = "Macro" })
  nvim_set_hl(0, "@parameter", { link = "Identifier" })
  nvim_set_hl(0, "@method", { link = "Function" })
  nvim_set_hl(0, "@field", { link = "Identifier" })
  nvim_set_hl(0, "@property", { link = "Identifier" })
  nvim_set_hl(0, "@constructor", { link = "Special" })
  nvim_set_hl(0, "@conditional", { link = "Conditional" })
  nvim_set_hl(0, "@repeat", { link = "Repeat" })
  nvim_set_hl(0, "@label", { link = "Label" })
  nvim_set_hl(0, "@operator", { link = "Operator" })
  nvim_set_hl(0, "@keyword", { link = "Keyword" })
  nvim_set_hl(0, "@exception", { link = "Exception" })
  nvim_set_hl(0, "@variable", { link = "Identifier" })
  nvim_set_hl(0, "@type", { link = "Type" })
  nvim_set_hl(0, "@type.definition", { link = "Typedef" })
  nvim_set_hl(0, "@storageclass", { link = "StorageClass" })
  nvim_set_hl(0, "@structure", { link = "Structure" })
  nvim_set_hl(0, "@namespace", { link = "Identifier" })
  nvim_set_hl(0, "@include", { link = "Include" })
  nvim_set_hl(0, "@preproc", { link = "PreProc" })
  nvim_set_hl(0, "@debug", { link = "Debug" })
  nvim_set_hl(0, "@tag", { link = "Tag" })

  -- Float terminal (https://github.com/voldikss/vim-floaterm)
  nvim_set_hl(0, "Floaterm", { link = "NormalFloat" })

  -- Notification (https://github.com/rcarriga/nvim-notify)
  nvim_set_hl(0, "NotifyERRORBorder", { fg = "#D66652" })
  nvim_set_hl(0, "NotifyWARNBorder", { fg = "#e59368" })
  nvim_set_hl(0, "NotifyINFOBorder", { fg = "#4e5a64" })
  nvim_set_hl(0, "NotifyDEBUGBorder", { fg = "#7F8E9D" })
  nvim_set_hl(0, "NotifyTRACEBorder", { fg = "#4e5a64" })
  nvim_set_hl(0, "NotifyERRORIcon", { fg = "#ba3d5a" })
  nvim_set_hl(0, "NotifyWARNIcon", { fg = "#814b00" })
  nvim_set_hl(0, "NotifyINFOIcon", { fg = "#2d6800" })
  nvim_set_hl(0, "NotifyDEBUGIcon", { fg = "#7F8E9D" })
  nvim_set_hl(0, "NotifyTRACEIcon", { fg = "#8787BF" })
  nvim_set_hl(0, "NotifyERRORTitle", { fg = "#ba3d5a" })
  nvim_set_hl(0, "NotifyWARNTitle", { fg = "#814b00" })
  nvim_set_hl(0, "NotifyINFOTitle", { fg = "#2d6800" })
  nvim_set_hl(0, "NotifyDEBUGTitle", { fg = "#7F8E9D" })
  nvim_set_hl(0, "NotifyTRACETitle", { fg = "#8787BF" })
  nvim_set_hl(0, "NotifyERRORBody", { link = "Normal" })
  nvim_set_hl(0, "NotifyWARNBody", { link = "Normal" })
  nvim_set_hl(0, "NotifyINFOBody", { link = "Normal" })
  nvim_set_hl(0, "NotifyDEBUGBody", { link = "Normal" })
  nvim_set_hl(0, "NotifyTRACEBody", { link = "Normal" })
end

return Colorscheme
