local set_hl = vim.api.nvim_set_hl

local Theme = {}

local function set_hl_basic()
  set_hl(0, "ColorColumn", { bg = "#2e383c" })
  set_hl(0, "Conceal", { fg = "#7a8478" })
  set_hl(0, "CurSearch", { fg = "#272e33" })
  set_hl(0, "Cursor", { fg = "#d3c6aa", bg = "#e67e80" })
  set_hl(0, "lCursor", { fg = "#d3c6aa", bg = "#e67e80" })
  -- set_hl(0, "CursorIM", {})
  set_hl(0, "CursorColumn", { bg = "#2e383c" })
  -- set_hl(0, "CursorLine", {})
  set_hl(0, "Directory", { fg = "#a7c080" })
  set_hl(0, "DiffAdd", { fg = "#3c4841" })
  set_hl(0, "DiffChange", { fg = "#384b55" })
  set_hl(0, "DiffDelete", { fg = "#493b40" })
  set_hl(0, "DiffText", { fg = "#272e33", bg = "#7fbbb3" })
  set_hl(0, "EndOfBuffer", { fg = "#272e33" })
  -- set_hl(0, "TermCursor", {})
  set_hl(0, "ErrorMsg", { fg = "#e67e80", bold = true, undercurl = true })
  set_hl(0, "WinSeparator", { fg = "#495156", bg = "#1e2326" })
  set_hl(0, "Folded", { fg = "#859289", bg = "#2e383c" })
  set_hl(0, "FoldColumn", { fg = "#7a8478" })
  set_hl(0, "SignColumn", { fg = "#d3c6aa" })
  set_hl(0, "IncSearch", { fg = "#272e33", bg = "#e67e80" })
  set_hl(0, "Substitute", { fg = "#272e33", bg = "#dbbc7f" })
  set_hl(0, "LineNr", { fg = "#9da9a0" })
  -- set_hl(0, "LineNrAbove", {})
  -- set_hl(0, "LineNrBelow", {})
  -- set_hl(0, "CursorLineNr", {})
  -- set_hl(0, "CursorLineFold", {})
  -- set_hl(0, "CursorLineSign", {})
  set_hl(0, "MatchParen", { fg = "#495156" })
  set_hl(0, "ModeMsg", { fg = "#d3c6aa", bold = true })
  -- set_hl(0, "MsgArea", {})
  -- set_hl(0, "MsgSeparator", {})
  set_hl(0, "MoreMsg", { fg = "#dbbc7f", bold = true })
  set_hl(0, "NonText", { fg = "#495156" })
  set_hl(0, "Normal", { fg = "#d3c6aa", bg = "#272e33" })
  set_hl(0, "NormalFloat", { fg = "#d3c6aa", bg = "#272e33" })
  set_hl(0, "FloatBorder", { fg = "#859289", bg = "#272e33" })
  set_hl(0, "FloatTitle", { fg = "#d3c6aa", bg = "#272e33", bold = true })
  set_hl(0, "FloatFooter", { fg = "#d3c6aa", bg = "#272e33", bold = true })
  set_hl(0, "NormalNC", { fg = "#d3c6aa", bg = "#1e2326" })
  set_hl(0, "Pmenu", { fg = "#d3c6aa", bg = "#374145" })
  set_hl(0, "PmenuSel", { fg = "#272e33", bg = "#a7c080" })
  set_hl(0, "PmenuKind", { fg = "#a7c080", bg = "#374145" })
  set_hl(0, "PmenuKindSel", { fg = "#a7c080", bg = "#374145" })
  set_hl(0, "PmenuExtra", { fg = "#9da9a0", bg = "#374145" })
  -- set_hl(0, "PmenuExtraSel", {})
  set_hl(0, "PmenuSbar", { bg = "#374145" })
  set_hl(0, "PmenuThumb", { bg = "#7a8478" })
  -- set_hl(0, "PmenuMatch", {})
  -- set_hl(0, "PmenuMatchSel", {})
  -- set_hl(0, "ComplMatchIns", {})
  set_hl(0, "Question", { fg = "#dbbc7f" })
  set_hl(0, "QuickFixLine", { fg = "#d699b6", bold = true })
  set_hl(0, "Search", { fg = "#272e33", bg = "#a7c080" })
  set_hl(0, "SnippetTabstop", {})
  set_hl(0, "SpecialKey", { fg = "#dbbc7f" })
  set_hl(0, "SpellBad", { sp = "#e67e80", undercurl = true })
  set_hl(0, "SpellCap", { sp = "#7fbbb3", undercurl = true })
  set_hl(0, "SpellLocal", { sp = "#83c092", undercurl = true })
  set_hl(0, "SpellRare", { sp = "#d699b6", undercurl = true })
  set_hl(0, "StatusLine", { fg = "#859289", bg = "#2e383c" })
  set_hl(0, "StatusLineNC", { fg = "#859289", bg = "#2e383c" })
  -- set_hl(0, "StatusLineTerm", {})
  -- set_hl(0, "StatusLineTermNC", {})
  set_hl(0, "TabLine", { fg = "#9da9a0", bg = "#414b50" })
  set_hl(0, "TabLineFill", { fg = "#859289", bg = "#2e383c" })
  set_hl(0, "TabLineSel", { fg = "#272e33", bg = "#a7c080" })
  set_hl(0, "Title", { fg = "#e69875", bold = true })
  set_hl(0, "Visual", { bg = "#5d4b55" })
  set_hl(0, "VisualNOS", { bg = "#5d4b55" })
  set_hl(0, "WarningMsg", { fg = "#dbbc7f", bold = true })
  set_hl(0, "Whitespace", { fg = "#495156" })
  set_hl(0, "WildMenu", { fg = "#272e33", bg = "#a7c080" })
  -- set_hl(0, "WinBar", {})
  set_hl(0, "WinBarNC", { fg = "#859289" })
end

local function set_hl_diagnostic()
  set_hl(0, "DiagnosticError", { bg = "#493b40", sp = "#e67e80", undercurl = true })
  set_hl(0, "DiagnosticWarn", { bg = "#45443c", sp = "#dbbc7f", undercurl = true })
  set_hl(0, "DiagnosticInfo", { bg = "#384b55", sp = "#7fbbb3", undercurl = true })
  set_hl(0, "DiagnosticHint", { bg = "#3c4841", sp = "#a7c080", undercurl = true })
  -- set_hl(0,'DiagnosticOk',{})
  set_hl(0, "DiagnosticVirtualTextError", { fg = "#e67e80" })
  set_hl(0, "DiagnosticVirtualTextWarn", { fg = "#dbbc7f" })
  set_hl(0, "DiagnosticVirtualTextInfo", { fg = "#7fbbb3" })
  set_hl(0, "DiagnosticVirtualTextHint", { fg = "#a7c080" })
  -- set_hl(0,'DiagnosticVirtualTextOk',{})
  set_hl(0, "DiagnosticUnderlineError", { bg = "#493b40", sp = "#e67e80", undercurl = true })
  set_hl(0, "DiagnosticUnderlineWarn", { bg = "#45443c", sp = "#dbbc7f", undercurl = true })
  set_hl(0, "DiagnosticUnderlineInfo", { bg = "#384b55", sp = "#7fbbb3", undercurl = true })
  set_hl(0, "DiagnosticUnderlineHint", { bg = "#3c4841", sp = "#a7c080", undercurl = true })
  -- set_hl(0,'DiagnosticUnderlineOk',{})
  set_hl(0, "DiagnosticFloatingError", { fg = "#e67e80" })
  set_hl(0, "DiagnosticFloatingWarn", { fg = "#dbbc7f" })
  set_hl(0, "DiagnosticFloatingInfo", { fg = "#7fbbb3" })
  set_hl(0, "DiagnosticFloatingHint", { fg = "#a7c080" })
  -- set_hl(0,'DiagnosticFloatingOk',{})
  set_hl(0, "DiagnosticSignError", { fg = "#e67e80" })
  set_hl(0, "DiagnosticSignWarn", { fg = "#dbbc7f" })
  set_hl(0, "DiagnosticSignInfo", { fg = "#7fbbb3" })
  set_hl(0, "DiagnosticSignHint", { fg = "#a7c080" })
  -- set_hl(0,'DiagnosticSignOk',{})
  -- set_hl(0,'DiagnosticDeprecated',{})
  set_hl(0, "DiagnosticUnnecessary", { bg = "#45443c", sp = "#dbbc7f", undercurl = true })
end

local function set_hl_treesitter()
  set_hl(0, "@variable", { fg = "#7fbbb3" })
  set_hl(0, "@variable.builtin", { fg = "#7fbbb3" })
  set_hl(0, "@variable.parameter", { fg = "#7fbbb3" })
  -- set_hl(0, "@variable.parameter.builtin", {})
  -- set_hl(0, "@variable.member", {})
  set_hl(0, "@constant", { fg = "#83c092" })
  set_hl(0, "@constant.builtin", { fg = "#dbbc7f" })
  set_hl(0, "@constant.macro", { fg = "#d699b6" })
  set_hl(0, "@module", { fg = "#e69875" })
  set_hl(0, "@module.builtin", { fg = "#e69875" })
  set_hl(0, "@label", { fg = "#e69875" })
  set_hl(0, "@string", { fg = "#a7c080" })
  -- set_hl(0, "@string.documentation", {})
  -- set_hl(0, "@string.regexp", {})
  -- set_hl(0, "@string.escape", {})
  set_hl(0, "@string.special", { fg = "#dbbc7f" })
  -- set_hl(0, "@string.special.symbol", {})
  -- set_hl(0, "@string.special.path", {})
  -- set_hl(0, "@string.special.url", {})
  set_hl(0, "@character", { fg = "#a7c080" })
  set_hl(0, "@character.special", { fg = "#dbbc7f" })
  set_hl(0, "@boolean", { fg = "#d699b6" })
  set_hl(0, "@number", { fg = "#d699b6" })
  set_hl(0, "@number.float", { fg = "#d699b6" })
  set_hl(0, "@type", { fg = "#dbbc7f" })
  set_hl(0, "@type.builtin", { fg = "#dbbc7f" })
  set_hl(0, "@type.definition", { fg = "#dbbc7f" })
  -- set_hl(0, "@attribute", {})
  -- set_hl(0, "@attribute.builtin", {})
  set_hl(0, "@property", { fg = "#7fbbb3" })
  set_hl(0, "@function", { fg = "#a7c080" })
  set_hl(0, "@function.builtin", { fg = "#a7c080" })
  -- set_hl(0, "@function.call", {})
  set_hl(0, "@function.macro", { fg = "#83c092" })
  set_hl(0, "@function.method", { fg = "#a7c080" })
  -- set_hl(0, "@function.method.call", {})
  set_hl(0, "@constructor", { fg = "#dbbc7f" })
  set_hl(0, "@operator", { fg = "#e69875" })
  set_hl(0, "@keyword", { fg = "#e67e80" })
  -- set_hl(0, "@keyword.coroutine", {})
  -- set_hl(0, "@keyword.function", {})
  -- set_hl(0, "@keyword.operator", {})
  -- set_hl(0, "@keyword.import", {})
  -- set_hl(0, "@keyword.type", {})
  -- set_hl(0, "@keyword.modifier", {})
  set_hl(0, "@keyword.repeat", { fg = "#e67e80" })
  -- set_hl(0, "@keyword.return", {})
  set_hl(0, "@keyword.debug", { fg = "#e69875" })
  set_hl(0, "@keyword.exception", { fg = "#e67e80" })
  set_hl(0, "@keyword.conditional", { fg = "#e67e80" })
  -- set_hl(0, "@keyword.conditional.ternary", {})
  -- set_hl(0, "@keyword.directive", {})
  set_hl(0, "@keyword.directive.define", { fg = "#d699b6" })
  set_hl(0, "@punctuation.delimiter", { fg = "#d3c6aa" })
  set_hl(0, "@punctuation.bracket", { fg = "#e67e80" })
  -- set_hl(0, "@punctuation.special", {})
  set_hl(0, "@comment", { fg = "#859289", italic = true })
  -- set_hl(0, "@comment.documentation", {})
  -- set_hl(0, "@comment.error", {})
  -- set_hl(0, "@comment.warning", {})
  set_hl(0, "@comment.todo", { fg = "#272e33", bg = "#dbbc7f", bold = true })
  -- set_hl(0, "@comment.note", {})
  -- set_hl(0, "@markup.strong", {})
  -- set_hl(0, "@markup.italic", {})
  -- set_hl(0, "@markup.strikethrough", {})
  -- set_hl(0, "@markup.underline", {})
  -- set_hl(0, "@markup.heading", {})
  -- set_hl(0, "@markup.heading.1", {})
  -- set_hl(0, "@markup.heading.2", {})
  -- set_hl(0, "@markup.heading.3", {})
  -- set_hl(0, "@markup.heading.4", {})
  -- set_hl(0, "@markup.heading.5", {})
  -- set_hl(0, "@markup.heading.6", {})
  -- set_hl(0, "@markup.quote", {})
  -- set_hl(0, "@markup.math", {})
  -- set_hl(0, "@markup.link", {})
  -- set_hl(0, "@markup.link.label", {})
  -- set_hl(0, "@markup.link.url", {})
  -- set_hl(0, "@markup.raw", {})
  -- set_hl(0, "@markup.raw.block", {})
  -- set_hl(0, "@markup.list", {})
  -- set_hl(0, "@markup.list.checked", {})
  -- set_hl(0, "@markup.list.unchecked", {})
  -- set_hl(0, "@diff.plus", {})
  -- set_hl(0, "@diff.minus", {})
  -- set_hl(0, "@diff.delta", {})
  set_hl(0, "@tag", { fg = "#e69875" })
  -- set_hl(0, "@tag.builtin", {})
  -- set_hl(0, "@tag.attribute", {})
  -- set_hl(0, "@tag.delimiter", {})
end

local function set_hl_lsp()
  -- set_hl(0, "LspReferenceText", {})
  -- set_hl(0, "LspReferenceRead", {})
  -- set_hl(0, "LspReferenceWrite", {})
  -- set_hl(0, "LspReferenceTarget", {})
  set_hl(0, "LspInlayHint", { fg = "#9da9a0" })
  set_hl(0, "LspCodeLens", { fg = "#7fbbb3", bg = "#384b55" })
  set_hl(0, "LspCodeLensSeparator", { fg = "#a7c080", bg = "#3c4841" })
  set_hl(0, "LspSignatureActiveParameter", { fg = "#272e33", bg = "#a7c080" })
end

function Theme.setup()
  set_hl_basic()
  set_hl_diagnostic()
  set_hl_treesitter()
  set_hl_lsp()
end

return Theme
